=== mozilla-mobile/mozilla-vpn-client/scripts/ci/jsonSchemas/addon.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "description": "The id of this addon"
    },
    "name": {
      "type": "string",
      "description": "The name of this addon"
    },
    "api_version": {
      "type": "string",
      "description": "The addon version framework"
    },
    "translatable": {
      "type": "boolean",
      "description": "Set it to false to make the addon not translatable. Default: true"
    },
    "type": {
      "type": "string",
      "description": "The type of the addon: tutorial, guide, i18n, message, replacer, ..."
    },
    "conditions": {
      "$ref": "conditions.json"
    },
    "state": {
      "type": "object",
      "description": "State properties related to the addon",
      "properties": {
        "session": {
          "type": "object",
          "description": "Session state is not synced across user devices and is not persisted throughout device sessions",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "boolean",
                  "string",
                  "number"
                ]
              },
              "default": {
                "type": [
                  "integer",
                  "string",
                  "boolean"
                ]
              }
            },
            "required": [
              "type",
              "default"
            ]
          }
        }
      }
    },
    "guide": {
      "$ref": "guide.json#"
    },
    "message": {
      "$ref": "message.json#"
    },
    "replacer": {
      "$ref": "replacer.json#"
    },
    "javascript": {
      "$ref": "javascript.json#"
    }
  },
  "required": [
    "id",
    "name",
    "api_version",
    "type"
  ]
}

=== mozilla-mobile/mozilla-vpn-client/tests/unit/addons/message2.json
{
  "api_version": "0.1",
  "id": "test_message_2",
  "name": "Test Message 2",
  "translatable": false,
  "type": "message",
  "conditions": { },
  "message": {
    "id": "test_message_2",
    "title": "Test Message 2 - Title",
    "subtitle": "Test Message 2 - Subtitle",
    "date": 1641406997,
    "blocks": [
    ]    
  }
}

=== mozilla-mobile/mozilla-vpn-client/tests/unit/addons/message4.json
{
  "api_version": "0.1",
  "id": "test_message_4",
  "name": "Test Message 4",
  "translatable": false,
  "type": "message",
  "conditions": {
    "end_time": 1599424544
  },
  "message": {
    "id": "test_message_4",
    "title": "Test Message 4 - Title",
    "subtitle": "Test Message 4 - Subtitle",
    "date": 1641406997,
    "blocks": []
  }
}
